# -*- coding: utf-8 -*-
"""nutritionist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lMJCmaOtg0PaHlDFheorqiFtDNts8W6

# Основная программа
1. Она принимает на вход список ингредиентов.
2. Она создает прогноз и выдает рейтинг с оценкой (невкусное, нормальное, вкусное) блюда, которое можно приготовить на основе списка переданных ингредиентов.
3. Она находит и выводит информацию обо всех питательных веществах (белках, жирах, натрии и т. д.) продуктов из списка, а также их объем в процентах от суточной нормы потребления.
4. Она отображает три рецепта блюд, в которых используется максимальное количество продуктов из списка, с указанием их оценки и ссылок, по которым пользователь сможет найти полную информацию.

Пример работы программы:

    $ ./nutritionist.py milk, honey, jam
    I. НАШ ПРОГНОЗ

    Невкусное. Хоть конкретно вам может быть и понравится блюдо из этих ингредиентов, но, на наш взгляд, это плохая идея – готовить блюдо из них. Хотели предупредить.

    II. ПИЩЕВАЯ ЦЕННОСТЬ
    Milk
    Protein – 6% of Daily Value
    Total Carbohydrate – 1% of Daily Value
    Total Fat – 1% of Daily Value
    Calcium – 12% of Daily Value
    …

    Honey
    …

    Jam
    …

    III. ТОП-3 ПОХОЖИХ РЕЦЕПТА:
    - Strawberry-Soy Milk Shake, рейтинг: 3.0, URL:https://www.epicurious.com/recipes/food/views/strawberry-soy-milk-shake-239217
    - …
    - …
"""

import recipes
import pandas as pd
import sys

print('\nРЕКОМЕНДАТЕЛЬНЫЙ СЕРВИС РЕЦЕПТОВ')
params = sys.argv
list_of_ingredients = params[1:]

exitcode = 0
while exitcode == 0:
    if len(params) > 1:
        list_of_ing = list_of_ingredients
        list_of_ingredients = ' '.join(list_of_ingredients)
        list_of_ing = [x.strip(',') for x in list_of_ing]
        params = ''
    else:
        print('\nПример ввода продуктов: almond, avocado, fish')
        list_of_ingredients = input('\nПеречислите ингредиенты на английском через запятую: ')
        list_of_ing = list_of_ingredients.split(",")
        list_of_ing = [x.strip(' ') for x in list_of_ing]
    df = pd.read_csv('data/recipes.csv')
    groceries = df.columns[6:]
    if len(list_of_ing) <= 1:
        print('\nСлишком мало ингредиентов. Введите 2 продукта и более')
        exitcode = 0
    elif 1 < len(list_of_ing) < 8:
        a = 0
        for i in list_of_ing:
            if i not in list(groceries):
                print(f'\nНеизвестный ингредиент "{i}", укажите другой')
            else: a = a + 1
        if a < len(list_of_ing) :
            print("\nПопробуйте выбрать что-нибудь из списка:", list(groceries))
            exitcode = 0

        if a == len(list_of_ing) :
            recipe = recipes.Forecast(list_of_ingredients)
            recipe.preprocess()
            rating_cat, text = recipe.predict_rating_category()
            print(f'\nI. НАШ ПРОГНОЗ\n\n{text}\n')

            nutrition = recipes.NutritionFacts(list_of_ingredients)
            facts = nutrition.retrieve()
            print('II. ПИЩЕВАЯ ЦЕННОСТЬ')
            for n in list_of_ing:
                print(f'\n{n}\n')
                for nn in range(len(facts)):
                    if facts['food_product'][nn] == n:
                        print(facts['nutrition'][nn],' - ',facts['value'][nn],'% of Daily Value')

            similarrecipe = recipes.SimilarRecipes(list_of_ingredients)
            similarrecipe.find_all()
            text_with_recipes = similarrecipe.top_similar()
            print('\nIII. ТОП-3 ПОХОЖИХ РЕЦЕПТА:\n')
            for i in range(3):
                print('- ',text_with_recipes['title'][i],', рейтинг: ',text_with_recipes['rating'][i],', URL: ',text_with_recipes['url'][i])

            dinner_name,dinner_food,dinner_url,dinner_rating,dinner_nutrition,lunch_name, lunch_food, lunch_url, lunch_rating, lunch_nutrition,breakfast_name, breakfast_food, breakfast_url, breakfast_rating, breakfast_nutrition = similarrecipe.menu_for_day()
            while exitcode == 0:
                select_ = input('\nСоставить меню на день? [Yes/no]: ')
                if select_ == '' or select_[0].lower() == 'y':
                    print('\nМЕНЮ НА ДЕНЬ')
                    print('\nЗАВТРАК\n---------------------')
                    print(breakfast_name,' (рейтинг: ',breakfast_rating,')')
                    print('\nИнгредиенты:')
                    for i in breakfast_food:
                        print('-',i)
                    print('\nNutrients:\n')
                    for j in range(len(breakfast_nutrition)):
                        print('-',breakfast_nutrition['nutrition'][j],': ',breakfast_nutrition['value'][j],'%')
                    print('URL: ', breakfast_url)
                    print('\nОБЕД\n---------------------')
                    print(lunch_name, ' (рейтинг: ', lunch_rating, ')')
                    print('\nИнгредиенты:')
                    for i in lunch_food:
                        print('-', i)
                    print('\nNutrients:\n')
                    for j in range(len(lunch_nutrition)):
                        print('-', lunch_nutrition['nutrition'][j], ': ', lunch_nutrition['value'][j], '%')
                    print('URL: ', lunch_url)
                    print('\nУЖИН\n---------------------')
                    print(dinner_name, ' (рейтинг: ', dinner_rating, ')')
                    print('\nИнгредиенты:')
                    for i in dinner_food:
                        print('-', i)
                    print('\nNutrients:\n')
                    for j in range(len(dinner_nutrition)):
                        print('-', dinner_nutrition['nutrition'][j], ': ', dinner_nutrition['value'][j], '%')
                    print('URL: ', dinner_url)
                    print('\nСпасибо за использование сервиса!')
                    exitcode = 2
                elif select_[0].lower() == 'n':
                    print('\nДо свидания! Спасибо за обращение.')
                    exitcode = 2
                else :
                    print('Неверный ввод!')
                    exitcode = 0
    else:
        print('Похожих рецептов не найдено. Возможно необходимо сократить кол-во ингредиентов')
        exitcode = 0
